# Generated by Django 5.1.6 on 2025-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_number', models.CharField(blank=True, max_length=100, null=True)),
                ('j1', models.IntegerField()),
                ('j2', models.IntegerField()),
                ('j3', models.IntegerField()),
                ('j4', models.IntegerField()),
                ('j5', models.IntegerField()),
                ('j6', models.IntegerField()),
            ],
        ),
    ]
