# Generated by Django 5.1.6 on 2025-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_joint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('reception', 'Reception'), ('teaching', 'Teaching')], default='reception', max_length=20)),
            ],
        ),
    ]
