# Generated by Django 5.1.6 on 2025-07-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joint_status',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
