# Generated by Django 5.1.6 on 2025-07-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='myapp.subject'),
        ),
    ]
