# Generated by Django 5.1.6 on 2025-07-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pdfdocument_module_name_pdfdocument_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='teaching_started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
