# Generated by Django 5.1.6 on 2025-07-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_teaching_teaching_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastpdf', to='myapp.pdfdocument')),
            ],
        ),
    ]
