# Generated by Django 5.1.6 on 2025-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_lastmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
