# Generated by Django 5.2.1 on 2025-07-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_facedetdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedetdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
