# Generated by Django 5.2.1 on 2025-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_facedetdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='Teaching/ppt/'),
        ),
    ]
