# Generated by Django 5.1.6 on 2025-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_pdfdocument_ppt_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joystick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=300, null=True)),
                ('distance', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
