# Generated by Django 5.1.6 on 2025-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestuers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
